const canvas=document.getElementById('game');
const ctx=canvas.getContext('2d');ctx.imageSmoothingEnabled=false;
let W=0,H=0,DPR=1,t=0;
const TW=64,TH=32,mapW=24,mapH=19;
const cam={x:0,y:0,z:1,drag:false,lx:0,ly:0,lock:false};
const tiles=[],ground=[],objects=[],structures=[],chars=[];
const base='assets/full_png/';
const img={tiles:{grass:[],shore:[],water:[]},trees:[],bushes:[],rocks:[],pebbles:[],houses:[],campfires:[],people:[],ready:false};
function loadImage(src){return new Promise(r=>{const im=new Image();im.onload=()=>r(im);im.onerror=()=>r(null);im.src=src})}
async function loadAssets(){try{const m=await fetch(base+'manifest.json?v=fullpng1').then(r=>r.json());const load=async arr=>{const out=[];for(const n of arr||[]){const im=await loadImage(base+n+'?v=fullpng1');if(im)out.push(im)}return out};img.tiles.grass=await load(m.tiles.grass);img.tiles.shore=await load(m.tiles.shore);img.tiles.water=await load(m.tiles.water);img.trees=await load(m.objects.trees);img.bushes=await load(m.objects.bushes);img.rocks=await load(m.objects.rocks);img.pebbles=await load(m.objects.pebbles);img.houses=await load(m.objects.houses);img.campfires=await load(m.objects.campfires);img.people=await load(m.objects.people);img.ready=img.tiles.grass.length&&img.tiles.shore.length&&img.tiles.water.length&&img.trees.length&&img.houses.length&&img.people.length;console.log('FULL PNG',img.ready,img)}catch(e){console.warn('full png missing',e)}}
loadAssets();
function choose(a,x,y){return a.length?a[Math.abs((x*37+y*19)|0)%a.length]:null}
function hash(x,y,s=0){let n=x*374761393+y*668265263+s*1442695041;n=(n^(n>>13))*1274126177;return((n^(n>>16))>>>0)/4294967295}
function rnd(a,b,x=1,y=1,s=0){return a+hash(x,y,s)*(b-a)}
function resize(){DPR=Math.min(devicePixelRatio||1,2);W=innerWidth*DPR|0;H=innerHeight*DPR|0;if(canvas.width!==W||canvas.height!==H){canvas.width=W;canvas.height=H;ctx.imageSmoothingEnabled=false;if(!cam.lock){cam.z=innerWidth<700?.82:1.06;cam.x=innerWidth<700?innerWidth*.5:innerWidth*.52;cam.y=innerWidth<700?245:140}}}
function iso(x,y,z=0){return{x:(x-y)*TW/2,y:(x+y)*TH/2-z}}
function getTile(x,y){return tiles.find(q=>q.x===x&&q.y===y)}
function isWater(x,y){const q=getTile(x,y);return !q||q.type==='water'}
function nearWater(x,y){for(let yy=-1;yy<=1;yy++)for(let xx=-1;xx<=1;xx++)if(isWater(x+xx,y+yy))return true;return false}
function near(x,y,px,py,r){return Math.hypot(x-px,y-py)<r}
function blocked(x,y){return near(x,y,8.7,11.2,1.7)||near(x,y,14.7,9.3,1.7)||near(x,y,12.2,10.6,1.35)||near(x,y,10.3,10.8,1.05)||near(x,y,11.2,10.7,1.05)||near(x,y,13.1,10.2,1.05)}
function add(list,kind,x,y,s=1,d=0){list.push({kind,x,y,s,depth:d||x+y+.7})}
function init(){for(let y=0;y<mapH;y++)for(let x=0;x<mapW;x++){let dx=x-mapW/2,dy=y-mapH/2,w=(hash(x,y,1)-.5)*.9+(hash(x+3,y-2,2)-.5)*.65,d=Math.sqrt(dx*dx*.86+dy*dy*1.18)+w;let type=d>9.7?'water':d>8.05?'shore':'grass';if((x>16&&y<8)||(x<3&&y>12)||(x>19&&y>13))type='water';if(type==='grass'&&hash(x,y,4)<.06)type='flower';if(type==='grass'&&hash(x,y,5)<.05)type='bushTile';tiles.push({x,y,type,h:type==='water'?-5:type==='shore'?-2:0})}
for(let y=0;y<mapH;y++)for(let x=0;x<mapW;x++){const q=getTile(x,y);if(!q||q.type==='water')continue;const nw=nearWater(x,y),blk=blocked(x,y);if(q.type!=='shore'&&!nw){const edge=x<5||y<4||x>18||y>13;if(edge&&hash(x,y,20)<.40)add(objects,'tree',x+rnd(.18,.68,x,y,21),y+rnd(.05,.42,x,y,22),rnd(.72,1.05,x,y,23),x+y+rnd(.1,.6,x,y,24));else if(hash(x,y,30)<.045)add(objects,'tree',x+rnd(.18,.68,x,y,31),y+rnd(.05,.42,x,y,32),rnd(.65,.9,x,y,33),x+y+rnd(.1,.6,x,y,34));if(hash(x,y,40)<.08)add(objects,'rock',x+rnd(.18,.8,x,y,41),y+rnd(.18,.72,x,y,42),rnd(.55,.82,x,y,43),x+y+.75);if(hash(x,y,50)<.07)add(objects,'bush',x+rnd(.18,.78,x,y,51),y+rnd(.18,.75,x,y,52),rnd(.65,.9,x,y,53),x+y+.78)}if(q.type==='shore'&&hash(x,y,66)<.25)add(objects,'pebble',x+rnd(.2,.8,x,y,67),y+rnd(.2,.8,x,y,68),rnd(.55,.75,x,y,69),x+y+.8);if((q.type==='grass'||q.type==='flower'||q.type==='bushTile')&&!blk&&hash(x,y,70)<.20)add(ground,'bush',x+rnd(.24,.76,x,y,90),y+rnd(.24,.76,x,y,100),rnd(.35,.55,x,y,110),x+y+.45)}
[['house',8.7,11.2,1],['house',14.7,9.3,.95],['camp',12.2,10.6,1]].forEach(a=>add(structures,...a));for(let i=0;i<8;i++){let x=9+(i%4)*1.15+rnd(-.22,.22,i,1),y=9.4+(i/4|0)*1.15+rnd(-.18,.2,i,2);chars.push({x,y,p:hash(i,2,1)*6.28,depth:x+y+1.15,variant:i})}}
function sprite(im,x,y,w,h){if(!im)return;ctx.drawImage(im,x-w/2,y-h,w,h)}
function drawTile(q){const p=iso(q.x,q.y,q.h),x=p.x,y=p.y;let arr=q.type==='water'?img.tiles.water:q.type==='shore'?img.tiles.shore:img.tiles.grass;let im=choose(arr,q.x,q.y);if(im)sprite(im,x,y+38,128,80)}
function drawObj(o){const p=iso(o.x,o.y,0);if(o.kind==='tree')sprite(choose(img.trees,o.x,o.y),p.x,p.y+22,82*o.s,106*o.s);else if(o.kind==='bush')sprite(choose(img.bushes,o.x,o.y),p.x,p.y+14,54*o.s,44*o.s);else if(o.kind==='rock')sprite(choose(img.rocks,o.x,o.y),p.x,p.y+12,46*o.s,36*o.s);else if(o.kind==='pebble')sprite(choose(img.pebbles,o.x,o.y),p.x,p.y+8,32*o.s,24*o.s);else if(o.kind==='house')sprite(choose(img.houses,o.x,o.y),p.x,p.y+24,112*o.s,104*o.s);else if(o.kind==='camp')sprite(choose(img.campfires,o.x,o.y),p.x,p.y+16,60*o.s,60*o.s)}
function drawPerson(ch){const p=iso(ch.x,ch.y,0),bob=Math.sin(t*.045+ch.p)*1.1;sprite(img.people.length?img.people[ch.variant%img.people.length]:null,p.x,p.y+10+bob,42,56)}
function drawList(list){list.sort((a,b)=>a.depth-b.depth).forEach(drawObj)}
function draw(){resize();t++;let g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,'#0e282a');g.addColorStop(.42,'#203d31');g.addColorStop(1,'#071614');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);ctx.save();ctx.scale(DPR*cam.z,DPR*cam.z);ctx.translate(cam.x/(cam.z*DPR)-40,cam.y/(cam.z*DPR)-18);tiles.sort((a,b)=>(a.x+a.y)-(b.x+b.y)).forEach(drawTile);drawList(ground);drawList(structures);drawList(objects);chars.sort((a,b)=>a.depth-b.depth).forEach(drawPerson);ctx.restore();ctx.fillStyle='rgba(20,40,25,.68)';ctx.fillRect(10*DPR,(innerHeight-28)*DPR,190*DPR,18*DPR);ctx.fillStyle=img.ready?'#d9ff9b':'#ffca7a';ctx.font=(10*DPR)+'px sans-serif';ctx.fillText('FULL PNG '+(img.ready?'ON':'MISSING'),16*DPR,(innerHeight-15)*DPR);ctx.globalAlpha=.03;ctx.fillStyle='#000';ctx.fillRect(0,0,W,H);ctx.globalAlpha=1;requestAnimationFrame(draw)}
canvas.addEventListener('pointerdown',e=>{cam.drag=true;cam.lock=true;cam.lx=e.clientX;cam.ly=e.clientY});canvas.addEventListener('pointermove',e=>{if(!cam.drag)return;cam.x+=e.clientX-cam.lx;cam.y+=e.clientY-cam.ly;cam.lx=e.clientX;cam.ly=e.clientY});canvas.addEventListener('pointerup',()=>cam.drag=false);canvas.addEventListener('pointercancel',()=>cam.drag=false);canvas.addEventListener('wheel',e=>{e.preventDefault();cam.z=Math.max(.45,Math.min(1.8,cam.z*(e.deltaY>0?.9:1.1)))},{passive:false});
init();draw();
